### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by cartalot** [martinredola/sublimetext2-codeigniter-completions#3]
hi -- i just read this new post on the thread you started in the codeigniter forum -- seems worth putting it in the read me, 
its definitely true for Sublime 2

http://codeigniter.com/forums/viewthread/213100/

Thanks, Martin, this is great.

For anyone having trouble: By default Sublime Text only triggers on characters, so if you’re trying to auto-complete by typing “$this” it isn’t going to work. Instead, try typing “this” and you should see the list pop up.

You can add

$ 

as a trigger in your preferences / settings :

"auto_complete_triggers": [ {"selector": "text.html", "characters": "<$"} ], 
The

< 

is there by default for HTML purposes, and the

$ 

is added for PHP.

**Comment by martinredola** [comment]
Sounds good, fancy altering readme.md and making a pull request?

**Comment by cartalot** [comment]
hi - this is the first time i've done this, so please let me know if i messed anything up -- thx
