### ISSUE TITLE
$this->session->userdata

### ISSUE THREAD

**Issue by eblanshey** [martinredola/sublimetext2-codeigniter-completions#5]
Hey there! How about adding $this->session->userdata?

Thanks.

**Comment by martinredola** [comment]
No problem, just add it and make a pull request.

I don't keep up to speed with CodeIgniter any longer as I now work almost exclusively using Laravel 4 or Symfony2.

**Comment by marcelod** [comment]
Hi, but will you see the pull-requests to https://github.com/mrmartineau/Placeholders/pulls? Tks

**Comment by martinredola** [comment]
Function now added.
